model_name_or_path: meta-llama/Llama-3.1-8B-Instruct
adapter_name_or_path: saves/llama3-8b-0417-rewrite18only/lora/sft
template: llama3
finetuning_type: lora
infer_backend: huggingface #choices： [huggingface, vllm]